### ISSUE TITLE
Exception in thread "main" org.apache.cassandra.db.KeyspaceNotDefinedException: Keyspace system_schema does not exist

### ISSUE THREAD

**Issue by rakeshtherani** [instaclustr/TTLRemover#4]
Hi Team , 

While executing TTL remover , its giving below given error . 

./TTLRemover /opt/cassandra/data/feb_data/table_1-9fbb0adc48f711e8a8b7e55aaace1278/ mc-56-big-Data.db   -p /opt/cassandra/data/feb_ttl_drop/

=======
error : 

Exception in thread "main" org.apache.cassandra.db.KeyspaceNotDefinedException: Keyspace system_schema does not exist
	at org.apache.cassandra.thrift.ThriftValidation.validateKeyspace(ThriftValidation.java:84)
	at org.apache.cassandra.thrift.ThriftValidation.validateColumnFamily(ThriftValidation.java:108)
	at org.apache.cassandra.cql3.statements.SelectStatement$RawStatement.prepare(SelectStatement.java:893)
	at org.apache.cassandra.cql3.statements.SelectStatement$RawStatement.prepare(SelectStatement.java:888)
	at org.apache.cassandra.cql3.QueryProcessor.getStatement(QueryProcessor.java:515)
	at org.apache.cassandra.cql3.QueryProcessor.parseStatement(QueryProcessor.java:224)
	at org.apache.cassandra.cql3.QueryProcessor.prepareInternal(QueryProcessor.java:268)
	at org.apache.cassandra.cql3.QueryProcessor.executeInternal(QueryProcessor.java:276)
	at org.apache.cassandra.schema.SchemaKeyspace.query(SchemaKeyspace.java:1239)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchKeyspacesWithout(SchemaKeyspace.java:861)
	at org.apache.cassandra.schema.SchemaKeyspace.fetchNonSystemKeyspaces(SchemaKeyspace.java:853)
	at org.apache.cassandra.config.Schema.loadFromDisk(Schema.java:136)
	at org.apache.cassandra.noTTL.TTLRemover.main(TTLRemover.java:160)

**Comment by phanirajl** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
getting this error.Could you please let me know fix for  this ...

**Comment by smiklosovic** [comment]
It most likely means that your database was completely empty. There needs to be populated db with schema on 2.x.
